### ISSUE TITLE
Modeliser le problème de livraison

### ISSUE THREAD

**Issue by JHilleri** [JHilleri/projet_recherche_developpement#2]
Pour les itinéraires de livraisons, définir:

- Les paramètres/données
- Les variables du problème (ce que tu peux modifier dans la solution)
- L'objectif à min/maximiser du problème
- Les contraintes sur la solution

La modélisation est faite dans le fichier : 
https://github.com/JHilleri/projet_recherche_developpement/blob/master/rapport/parts/modelisation/index.tex

Corrections à apporter a la modélisation :
- [x] [Rapport_09_oct.pdf](https://github.com/JHilleri/projet_recherche_developpement/blob/fe1aa596decfab8be35326a5ecbb88300ddf6fb4/Rapport_Hugo/Rapport_09_oct.pdf )

- [x] Rédaction du document en latex

**Comment by HugoChevroton** [comment]
Pour valider:
Pour la contrainte sur les D_j, rajoute l'intervalle de variation des var j_1 et j_2.
Pour la dernière contrainte : D_j >= D_0j + f_j
==> ces deux erreurs combinées font qu'il peut y avoir une erreur sur la date de livraison du premier job d'un batch (qui pourrait valoir f_j)
Optionnel : supprime PC_j^local ainsi que la contrainte inutile
